version: '3'

services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
    command: tail -f /dev/null

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - ./data:/var/lib/mysql
    command: yes database

  users:
    build:
      context: .
      dockerfile: Dockerfile-users
    command: while true; do echo users; done
